### ISSUE TITLE
Refreshing data?

### ISSUE THREAD

**Issue by JMSerruya** [tink-ab/tink-connect-ios-example#5]
Hello!. I'm using Tink to aggregate investment accounts of my users.

I am wondering what the best way to refresh their accounts. For example, if an user connects their Nordnet and Avanza accounts, what's the best way for my app to refresh that data?, is there a way to only have to use BankID once or do I need to trigger the flow for each time they want to refresh data and for each specific bank?

An example on refreshing data would be great! Thank you

**Comment by lipka** [comment]
Hello @JMSerruya!

> I am wondering what the best way to refresh their accounts. For example, if an user connects their Nordnet and Avanza accounts, what's the best way for my app to refresh that data?, is there a way to only have to use BankID once or do I need to trigger the flow for each time they want to refresh data and for each specific bank?

Yes, at the moment you would need to go through the Tink Link flow to retrieve new data again.

> An example on refreshing data would be great! Thank you

I'll make sure we add something around this in our docs. Thanks for the feedback!
