### ISSUE TITLE
SwiftUI

### ISSUE THREAD

**Issue by alelordelo** [tink-ab/tink-connect-ios-example#7]
Any plans for a SwiftUI version? 

Is it possible to connect corporate SEB accounts?

**Comment by lipka** [comment]
Hey @alelordelo!

Yes, we will add an example SwiftUI integration soon.

Please reach out using the following link regarding corporate accounts: https://tinkab.atlassian.net/servicedesk/customer/portal/5

**Comment by alelordelo** [comment]
awesome, any ETA for that?

**Comment by lipka** [comment]
@alelordelo I think you can expect something within the next 1-2 months.

**Comment by alelordelo** [comment]
awesome! I would be happy to contribute to project
